"""empty message

Revision ID: 094a033c4c49
Revises: a60ea7db9b6f
Create Date: 2022-12-15 21:57:00.197211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094a033c4c49'
down_revision = 'a60ea7db9b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Unicode(length=255), nullable=True),
    sa.Column('date', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('сomment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('сomment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('marker_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comment')
    # ### end Alembic commands ###
