"""empty message

Revision ID: 4e980ac3570f
Revises: a60ea7db9b6f
Create Date: 2022-12-08 19:59:40.718569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e980ac3570f'
down_revision = 'a60ea7db9b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Unicode(length=255), nullable=True),
    sa.Column('date', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('сomment')
    with op.batch_alter_table('marker', schema=None) as batch_op:
        batch_op.alter_column('x_axis',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('y_axis',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marker', schema=None) as batch_op:
        batch_op.alter_column('y_axis',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('x_axis',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('сomment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('marker_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comment')
    # ### end Alembic commands ###
