"""empty message

Revision ID: 66591e24d301
Revises: 
Create Date: 2022-11-26 22:41:18.237386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66591e24d301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('path', sa.Unicode(length=255), nullable=True),
    sa.Column('max_zoom', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    op.drop_table('project')
    # ### end Alembic commands ###
