"""empty message

Revision ID: a60ea7db9b6f
Revises: 66591e24d301
Create Date: 2022-12-08 15:56:54.365978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60ea7db9b6f'
down_revision = '66591e24d301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('header', sa.Unicode(length=255), nullable=True),
    sa.Column('text', sa.Unicode(length=255), nullable=True),
    sa.Column('x_axis', sa.Integer(), nullable=True),
    sa.Column('y_axis', sa.Integer(), nullable=True),
    sa.Column('color', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('сomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Unicode(length=255), nullable=True),
    sa.Column('date', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('сomment')
    op.drop_table('marker')
    op.drop_table('layer')
    op.drop_table('user')
    # ### end Alembic commands ###
